/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/neptune/new/internal/utils/git.py:34: UserWarning: GitPython could not be initialized
  warnings.warn("GitPython could not be initialized")
/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/neptune/new/internal/utils/git.py:34: UserWarning: GitPython could not be initialized
  warnings.warn("GitPython could not be initialized")
/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/neptune/new/internal/utils/git.py:34: UserWarning: GitPython could not be initialized
  warnings.warn("GitPython could not be initialized")
/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/numpy/lib/shape_base.py:379: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  res = asanyarray(func1d(inarr_view[ind0], *args, **kwargs))
Traceback (most recent call last):
  File "/data/home/dhwon/GenerativeMTD/train.py", line 81, in <module>
    train_GVAE(opt)
  File "/data/home/dhwon/GenerativeMTD/train.py", line 27, in train_GVAE
    model.fit(df,discrete_columns = ("Sex", "Recerational.Athlete", "Birth.Control","PsychDistress"))
  File "/data/home/dhwon/GenerativeMTD/GVAE.py", line 456, in fit
    plt.plot(np.arange(self.opt.epochs),VAEGLoss,label='Generator Loss')
  File "/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/matplotlib/pyplot.py", line 3019, in plot
    return gca().plot(
  File "/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 1605, in plot
    lines = [*self._get_lines(*args, data=data, **kwargs)]
  File "/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 315, in __call__
    yield from self._plot_args(this, kwargs)
  File "/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/matplotlib/axes/_base.py", line 491, in _plot_args
    y = _check_1d(xy[1])
  File "/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/matplotlib/cbook/__init__.py", line 1339, in _check_1d
    return np.atleast_1d(x)
  File "<__array_function__ internals>", line 5, in atleast_1d
  File "/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/numpy/core/shape_base.py", line 65, in atleast_1d
    ary = asanyarray(ary)
  File "/data/home/dhwon/.conda/envs/deepmtd/lib/python3.9/site-packages/torch/_tensor.py", line 643, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
Waiting for the remaining 602 operations to synchronize with Neptune. Do not kill this process.
